try to fix missing osal.h
In file included from drivers/misc/mediatek/connectivity/common/common_detect/wmt_gpio.c:15:0:
>> drivers/misc/mediatek/connectivity/common/common_detect/wmt_gpio.h:24:10: fatal error: osal.h: No such file or directory
 \#include "osal.h"

Reported-by: kbuild test robot <lkp@intel.com>